package helper

import (
	"time"

	gonanoid "github.com/matoous/go-nanoid/v2"
	t "github.com/tonkla/autotp/types"
)

// Now13 returns a millisecond Unix timestamp (13 digits)
func Now13() int64 {
	return time.Now().UnixNano() / 1e6
}

// GenID returns a random string, generated by NanoID
func GenID(size int) (string, error) {
	if size == 0 {
		size = 13
	}
	return gonanoid.Generate("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", size)
}

// CalcSLStop calculates a stop price of the stop loss price
func CalcSLStop(side string, sl float64, trigger float64) float64 {
	if trigger == 0 {
		trigger = 0.002
	}
	if side == t.OrderSideBuy {
		return sl + sl*trigger
	}
	return sl - sl*trigger
}

// CalcTPStop calculates a stop price of the take profit price
func CalcTPStop(side string, tp float64, trigger float64) float64 {
	if trigger == 0 {
		trigger = 0.002
	}
	if side == t.OrderSideBuy {
		return tp - tp*trigger
	}
	return tp + tp*trigger
}

// Reverse returns the opposite side
func Reverse(side string) string {
	if side == t.OrderSideBuy {
		return t.OrderSideSell
	}
	return t.OrderSideBuy
}
